apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"  # Deploy early
spec:
  project: default
  sources:
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.18.6
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $repo/core-infrastructure/sealed-secrets/values.yaml

    - repoURL: 'https://github.com/Thewolf2068/homelab.git' # <-- update this
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
