apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor
  resources:
    requests:
      storage: 750Mi
