apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-{{ .Chart.Name }}-smb
spec:
  capacity:
    storage: {{ .Values.global.smbStorageCapacity }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid={{ .Values.global.securityContext.runAsUser }}
    - gid={{ .Values.global.securityContext.runAsGroup }}
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: "{{ .Chart.Name }}-smb"
    volumeAttributes:
      source: "//u543033.your-storagebox.de/backup"
    nodeStageSecretRef:
      name: hetzner-smb-creds
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Chart.Name }}-smb
spec:
  volumeName: pv-{{ .Chart.Name }}-smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.smbStorageCapacity }}
  storageClassName: smb
