apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshotter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Thewolf2068/homelab.git'
    targetRevision: HEAD
    path: core-infrastructure/csi-snapshotter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
