# argocd-apps/core-infrastructure.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Thewolf2068/homelab.git'
    targetRevision: HEAD
    path: core-infrastructure
    directory:
      recurse: true 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
