apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: 'https://helm.traefik.io/traefik'
      chart: traefik
      targetRevision: 26.0.0
      helm:
        valueFiles:
          - $repo/core-infrastructure/traefik/values.yaml

    - repoURL: 'https://github.com/Thewolf2068/homelab.git' # <-- update this
      targetRevision: HEAD
      path: core-infrastructure/traefik/manifests
      ref: repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
