deployment:
  podSecurityContext:
    fsGroup: 65532
  replicas: 1

ports:
  web:
    hostPort: 80
    redirectTo:
      port: websecure
  websecure:
    hostPort: 443
    tls:
      enabled: true

service:
  type: ClusterIP
# Injects the Cloudflare API token into Traefik's environment
envFrom:
  - secretRef:
      name: cloudflare-api-token

additionalArguments:
  - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
  - "--certificatesresolvers.cloudflare.acme.email=malenia@miquella.dev"
  - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
  - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

persistence:
  enabled: true
  name: traefik-acme-storage
  path: /data
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: longhorn

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
