deployment:
  podSecurityContext:
    fsGroup: 65532
  replicas: 3

ports:
  web:
    hostPort: 80
    redirectTo:
      port: websecure
  websecure:
    hostPort: 443
    tls:
      enabled: true

service:
  type: ClusterIP

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
