apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        pre.hook.backup.velero.io/container: {{ .Chart.Name }}
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -STOP $(pidof {{ .Chart.Name }}|| echo 1)"]'
        post.hook.backup.velero.io/container: {{ .Chart.Name }}
        post.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -CONT $(pidof {{ .Chart.Name }}|| echo 1)"]'
    spec:
      securityContext:
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        fsGroup: {{ .Values.global.securityContext.runAsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
              subPath: media/
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-data-pvc
        - name: media
          persistentVolumeClaim:
            claimName: pvc-{{ .Chart.Name }}-smb
