apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://charts.longhorn.io'
      chart: longhorn
      targetRevision: 1.8.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $repo/core-infrastructure/longhorn/values.yaml
    - repoURL: 'https://github.com/Thewolf2068/homelab.git'
      targetRevision: HEAD
      path: core-infrastructure/longhorn/manifests
      ref: repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
