preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Delete

image:
  repository: longhornio/longhorn-manager
  tag: v1.12.1@sha256:83b79f57043fe1405e68bc0d4c7987accbc6bb512def3e0db12b31966c070801

csi:
  kubeletRootDir: /var/lib/kubelet

defaultSettings:
  defaultReplicaCount: 3
  storageMinimalAvailablePercentage: 10
  storageReservedPercentageForDefaultDisk: 10
  guaranteedEngineManagerCPU: 5
  guaranteedReplicaManagerCPU: 5

