preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Delete

image:
  repository: longhornio/longhorn-manager
  tag: v1.12.0@sha256:fd245bae2e8254ed475073410f8462e95fab8783dd12d1c084777b5ab53bfb86

csi:
  kubeletRootDir: /var/lib/kubelet

defaultSettings:
  defaultReplicaCount: 3
  storageMinimalAvailablePercentage: 10
  storageReservedPercentageForDefaultDisk: 10
  guaranteedEngineManagerCPU: 5
  guaranteedReplicaManagerCPU: 5

