apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-whitelist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Chart.Name }}-whitelist
    creationPolicy: Owner
  data:
    - secretKey: names
      remoteRef:
        key: {{ .Chart.Name }}-whitelist/names
