global:
  domain: "miquella.dev"
  smbStorageCapacity: "1Ti"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  securityContextHomeOps:
    runAsUser: 65534
    runAsGroup: 65534

navidrome:
  enabled: true
  image:
    repository: "deluan/navidrome"
    tag: "0.62.0@sha256:c4b5cb36a790b3eb63ca6a68bbe2fe149c2d7fa2e586f7a480e61db630e6664b"
  port: "4533"
  subdomain: "navidrome"

prowlarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/prowlarr"
    tag: "2.5.0.5422@sha256:91aad3d438568387d0731fd2b812d1812cf15c3738c7eedca60c04186f35fd5d"
  port: "9696"
  subdomain: "prowlarr"

jellyfin:
  enabled: true
  image:
    repository: "jellyfin/jellyfin"
    tag: "10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db"
  port: "8096"
  subdomain: "jellyfin"

sabnzbd:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sabnzbd"
    tag: "5.0.4@sha256:457be5fad7b83c338a981f1945e1ecae2dedd0cc81cdd2992673b0dc84fc2890"
  port: "8080"
  subdomain: "sabnzbd"

radarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/radarr"
    tag: "6.2.1.10461@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e"
  port: "7878"
  subdomain: "radarr"

radarr-anime:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/radarr"
    tag: "6.2.1.10461@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e"
  port: "7878"
  subdomain: "radarr-anime"

sonarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sonarr"
    tag: "4.0.18.2978@sha256:2cd77fb3d81909a734d61bb8f71462044cb9d2f187e626a28a05a5c4e4be8fd2"
  port: "8989"
  subdomain: "sonarr"

sonarr-anime:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sonarr"
    tag: "4.0.18.2978@sha256:2cd77fb3d81909a734d61bb8f71462044cb9d2f187e626a28a05a5c4e4be8fd2"
  port: "8989"
  subdomain: "sonarr-anime"

qbittorrent:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/qbittorrent"
    tag: "5.2.2@sha256:24f2d793cb7f7a93e755e5d22e533be818e62eadc864f4a82315b901b6ffe807"
  port: "8080"
  subdomain: "qbittorrent"

seerr:
  enabled: true
  image:
    repository: "ghcr.io/seerr-team/seerr"
    tag: "v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8"
  port: "5055"
  subdomain: "seerr"

maintainerr:
  enabled: true
  image:
    repository: "ghcr.io/maintainerr/maintainerr"
    tag: "3.16.0@sha256:0829781eb442f93065edda051d4a87f343a1cf05f7ea03635e87306fc786f087"
  port: "6246"
  subdomain: "maintainerr"

syncyomi:
  enabled: true
  image:
    repository: "ghcr.io/syncyomi/syncyomi"
    tag: "v1.1.12@sha256:262993cce3ff38b96845a802432535d5898c7d623097a4c6bcf00af338c156d0"
  port: "8282"
  subdomain: "syncyomi"

freshrss:
  enabled: true
  image:
    repository: "lscr.io/linuxserver/freshrss"
    tag: "1.29.1-ls313@sha256:94bdfaadb6da49acc62179a0d16de30a326601b1c5d4f439c8cfd83d24af21a8"
  port: "80"
  subdomain: "rss"
