global:
  domain: "miquella.dev"
  smbStorageCapacity: "1Ti"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

navidrome:
  enabled: true
  image: "deluan/navidrome"
  imageTag: "0.61.2"
  port: "4533"
  subdomain: "navidrome"

prowlarr:
  enabled: true
  image: "home-operations/prowlarr"
  imageTag: "2.4.0.5397"
  imageDigest: "sha256:6fdfd467c60cc00210121ac2ecf663a310eaec834429d75a190e98be645574ef"
  port: "9696"
  subdomain: "prowlarr"

jellyfin:
  enabled: true
  image: "jellyfin/jellyfin"
  imageTag: "10.11.11"
  port: "8096"
  subdomain: "jellyfin"
