global:
  domain: "miquella.dev"
  smbStorageCapacity: "1Ti"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  securityContextHomeOps:
    runAsUser: 65534
    runAsGroup: 65534

navidrome:
  enabled: true
  image:
    repository: "deluan/navidrome"
    tag: "0.64.2@sha256:38dc2727bfcfd5ede290f8ada114fc90368146f265ae4701ddddbcbe2a44ee52"
  port: "4533"
  subdomain: "navidrome"

prowlarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/prowlarr"
    tag: "2.6.5.5623@sha256:6ec8808a8c8fc5c53928d01ac6acbfb0a3f87054aa438e31de9d300b39b446f5"
  port: "9696"
  subdomain: "prowlarr"

jellyfin:
  enabled: true
  image:
    repository: "jellyfin/jellyfin"
    tag: "10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db"
  port: "8096"
  subdomain: "jellyfin"

sabnzbd:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sabnzbd"
    tag: "5.1.3@sha256:b1795982db498ed5691a7b1231f0fac7eed2a1d53e9c81b8e834d02695e76104"
  port: "8080"
  subdomain: "sabnzbd"

radarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/radarr"
    tag: "6.4.4.10685@sha256:be53998a2d39cfa3c3315b70c7509a6a1f2a10c3aee9337653efc9f4c970430e"
  port: "7878"
  subdomain: "radarr"

radarr-anime:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/radarr"
    tag: "6.4.4.10685@sha256:be53998a2d39cfa3c3315b70c7509a6a1f2a10c3aee9337653efc9f4c970430e"
  port: "7878"
  subdomain: "radarr-anime"

sonarr:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sonarr"
    tag: "4.0.20.3012@sha256:1f19eb5e0f421418c1a956bbe01310a0141423afe28bd9a4b1dcb8629ff2bce2"
  port: "8989"
  subdomain: "sonarr"

sonarr-anime:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/sonarr"
    tag: "4.0.20.3012@sha256:1f19eb5e0f421418c1a956bbe01310a0141423afe28bd9a4b1dcb8629ff2bce2"
  port: "8989"
  subdomain: "sonarr-anime"

qbittorrent:
  enabled: true
  image:
    repository: "ghcr.io/home-operations/qbittorrent"
    tag: "5.2.4@sha256:9307627e03981d5473aa31175ea76ed56ea3752333ca49d601b6af45e281e7ba"
  port: "8080"
  subdomain: "qbittorrent"

seerr:
  enabled: true
  image:
    repository: "ghcr.io/seerr-team/seerr"
    tag: "v3.5.0@sha256:27602401178d54f1964442287b9f23f67a3fa2252645ee8065839ea1c3f69e45"
  port: "5055"
  subdomain: "seerr"

maintainerr:
  enabled: true
  image:
    repository: "ghcr.io/maintainerr/maintainerr"
    tag: "3.30.1@sha256:8251a1f0ba5d71acc878846a727fba566ec87cbfbf6a914fb881a5953af53d46"
  port: "6246"
  subdomain: "maintainerr"

syncyomi:
  enabled: true
  image:
    repository: "ghcr.io/syncyomi/syncyomi"
    tag: "v1.5.8@sha256:2d54fcff1d3fc5b05aee514c6fc1c8a66d6346038ff838192ed480348b2fd961"
  port: "8282"
  subdomain: "syncyomi"

freshrss:
  enabled: true
  image:
    repository: "lscr.io/linuxserver/freshrss"
    tag: "1.29.1-ls313@sha256:94bdfaadb6da49acc62179a0d16de30a326601b1c5d4f439c8cfd83d24af21a8"
  port: "80"
  subdomain: "rss"


calibre:
  enabled: true
  image:
    repository: "lscr.io/linuxserver/calibre"
    tag: "9.15.0@sha256:c97f86a5acc3372d5e25e75b4c98d1bffa64e70d4c413554beb1e554ae109187"
  port: "8080"
  subdomain: "calibre"

syncthing:
  enabled: true
  image:
    repository: "ghcr.io/syncthing/syncthing"
    tag: "2.1.5@sha256:397aa00b92b48d65540ea3ae3cbf271b87bdccbe07a0b7bd7d2debc3a7b29138"
  port: "8384"
  subdomain: "sync"

profilarr:
  enabled: true
  image:
    repository: "ghcr.io/dictionarry-hub/profilarr"
    tag: "2.2.0@sha256:ddcdd0f340043c2ec0a85ca74b9a6be9be42b1c0288c75fc36a26a43f695860b"
  port: 6868
  subdomain: "profilarr"

n8n:
  enabled: true
  image: 
    repository: "ghcr.io/n8n-io/n8n"
    tag: "2.43.0@sha256:c6a3a0461d1d3ffc16d849adf57606c2b028667ade70cce2faa2ff094734873c"
  port: 5678
  subdomain: "n8n"

ntfy:
  enabled: true
  image:
    repository: "binwiederhier/ntfy"
    tag: "v2.28@sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da"
  port: 80
  subdomain: "ntfy"

uptime-kuma:
  enabled: true
  image:
    repository: "ghcr.io/louislam/uptime-kuma"
    tag: "2.5.5@sha256:c74379ac4509ce2d2c2633f509e67003ee2e45b6e995c5e43fc101f45a0e1fbe"
  port: 3001
  subdomain: "uptime"
