---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-smb-creds
  namespace: kube-system
spec:
  encryptedData:
    password: AgCuXh6LIspWdqUjp9aR7hJ57+Y5zxUqq4IVd//94PUnP+hF0+rvfuirFTvUnLnQ6B/YV6VZ8WG/gZBcgT2zmIWhqSeOlQwM5a6zaaRdPXSOdrg+j3k5Gstp6Hs6YiP8//M2QjTMHpEW5FObz27uAMMPImCbwv6pyGCKaSEerxs8wPEXsPn1loi8BR8bau37+GuABUB7DGZoJQxGRg3D50y0+31TcCeaptqjmZkBG4SIblisPFRIE6k1nJ1tIHeC1VUWIra6fUm+wq/9d0Dg6Bj/Ai0+0e6N1vqVFeh3OPVB8+88HwBt09YGSW/adCkNdgbkAVVaa0LZoXf6Ab/IRnPHd+V/qhFKH+dJx0bIPL3wQSeg0N5kobv8Wn0tPNFVWCporjapevy1H6mvjS0b3AfcXrhhlVN6+joAxZy7M9+pMP8KM4Ru0IUsPjxnSe/AUlfog1sptwjFHOGF8IzK305FK9oHUkFRap0RdJYSS9upIt033ZvxbXWy3Bl6BOz7xPwgMJiMghMgmCBid4Bo9rhHmvIjAgRDXwO0UD2kY2v/hcGhH1n+SvyLVY21vAOxMb1k733PdKDbquQoutqMwYu197UW6RTv7b4FVyrqgr2UW1Lp+CgT5KuTA7WslVs1+iZP+MZhiUAEgO6T0JRhfYKMTQAbLvd5Ejoti0Tc5/5UETyLZ8frIEzOG05mBBDm7Y/tlvqPDOiVlAWXm7VcpPI=
    username: AgBwEIUy8R3OlFHwr/k+u8awS0TvAV+gE2c9UblNaHNPEMBYl2uRAnHKV5HEwfCOGMKF0wpk5DEt6SaweH0SIhBRQ5s1XjxUTGygvdxUmtLXYghwDYikFR9HDTja8ktURFnC5XFiWv4mnfc2bsx8ABc1iva/dUsZfIGHJ41bpbUVtdtVaPmZiZ7/Ts/wC8jkytF2oLCdGFCzdM+7YQBFyb0fAnVxyZZWeFG7mxcPSJDAAWCMN/uvkK3a7in0759+NdV4oVW3T4VNd6FHu/B+2CT7VedCtEAjLtZmVJqkKqCn4sfKgGYxlrZLZH50f1hs++H++ICOPLAiKu+uKftgNHwheVCH2uy6Z7KUF4OUjmOWSmoaG9+Gl480og7zc9IYfG/krImp+v8eoB2huMN9R3JnN+FbvKGTNm6waSA5JQ2tgNfvpFe2gmo7F+YvZMq8AaBh0wD4JE5O3fqHNct0CbS6coGO4KSj3Wx2C6Fk8Q6rM5xgXJlYss79w5F/xpms4vXk/fhpKFqHIsIdoaRL1gWDEjqsWj+O4ShVfqY47dkPbC0lIha3VTVfSm6/pGce/JgVa8RF9C+WNWSt7Qt95e8axkBldEzCPRzhUR5vo77Np42eKgsd8hKdhUukqOjrqwDTtGBiuvWXUFreu0feRAHMSyCyhpgROoKMO1H0kP3x8T/HUu2v7wxYubCO8a/kAibc2z3wnstp
  template:
    metadata:
      name: hetzner-smb-creds
      namespace: kube-system
