apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-smb-creds
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hetzner-smb-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: hetzner-storagebox/username
    - secretKey: password
      remoteRef:
        key: hetzner-storagebox/password
