apiVersion: v1
kind: PersistentVolume
metadata:
  name: hetzner-smb-global-pv
spec:
  capacity:
    storage: 1Ti # K8s requirement, not enforced by SMB
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hetzner-smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: hetzner-smb-root-share # Unique global identifier for this volume
    volumeAttributes:
      source: "//u543033.your-storagebox.de/backup"
    nodeStageSecretRef:
      name: hetzner-smb-creds
      namespace: kube-system
