apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
      annotations:
        pre.hook.backup.velero.io/container: navidrome
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -STOP $(pidof navidrome || echo 1)"]'
        post.hook.backup.velero.io/container: navidrome
        post.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -CONT $(pidof navidrome || echo 1)"]'
    spec:
      securityContext:
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        fsGroup: {{ .Values.global.securityContext.runAsGroup }}
      containers:
        - name: navidrome
          image: deluan/navidrome:{{ .Values.imageTag }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
              subPath: media/music/Library
              readOnly: false
      
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data-pvc
        - name: music
          persistentVolumeClaim:
            claimName: pvc-navidrome-smb
