configuration:
  backupStorageLocation:
    - name: default
      provider: velero.io/aws
      bucket: homelab-backup
      config:
        region: auto
        s3ForcePathStyle: true
        s3Url: https://ba7af738ac3fcf781135c6b598a7f096.r2.cloudflarestorage.com
  volumeSnapshotLocation:
    - name: default
      provider: driver.longhorn.io
  defaultSnapshotMoveData: true

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.4@sha256:c85a7fa803569e3128c33e4f5766f84ab156c8d171c9f1dd2715581d45ce98fa
    volumeMounts:
      - mountPath: /target
        name: plugins


deployNodeAgent: true

nodeAgent:
  containerSecurityContext:
    privileged: true

credentials:
  useSecret: true
  existingSecret: velero-s3-credentials

upgradeCRDs: false
kubectl:
  image:
    repository: alpine/kubectl
    tag: 1.37.0@sha256:601225d448500d59d19877e8e61bb861df48bd71373067bfbdf328aa74feb46a

schedules:
  media-pvc-backup:
    disabled: false
    schedule: "0 3 * * *" # Daily at 3 AM
    template:
      includedNamespaces:
        - media
      includedResources:
        - persistentvolumeclaims
        - persistentvolumes
      snapshotMoveData: true
      resourcePolicy:
        kind: configmap
        name: longhorn-volume-policy
