configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
    - name: default
      provider: velero.io/aws
      bucket: homelab-backup
      config:
        region: auto
        s3ForcePathStyle: true
        s3Url: https://ba7af738ac3fcf781135c6b598a7f096.r2.cloudflarestorage.com
  volumeSnapshotLocation: []


initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.1
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v1.15.2
    volumeMounts:
      - mountPath: /target
        name: plugins


deployNodeAgent: true

nodeAgent:
  containerSecurityContext:
    privileged: true

credentials:
  useSecret: true
  existingSecret: velero-s3-credentials

upgradeCRDs: false
kubectl:
  image:
    repository: bitnami/kubectl
    tag: latest


schedules:
  media-pvc-backup:
    disabled: false
    schedule: "0 3 * * *" # Daily at 3 AM
    template:
      includedNamespaces:
        - media
      includedResources:
        - persistentvolumeclaims
        - persistentvolumes
      
      resourcePolicy:
        kind: configmap
        name: longhorn-volume-policy

