configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
    - name: default
      provider: velero.io/aws
      bucket: homelab-backup
      config:
        region: auto
        s3ForcePathStyle: true
        s3Url: https://ba7af738ac3fcf781135c6b598a7f096.r2.cloudflarestorage.com
  volumeSnapshotLocation: []

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.1@sha256:3b0c402e0d55eb797a7ebe1f2525f18bdcdca8ee826680cd2d7cf657071e9d58
    volumeMounts:
      - mountPath: /target
        name: plugins


deployNodeAgent: true

nodeAgent:
  containerSecurityContext:
    privileged: true

credentials:
  useSecret: true
  existingSecret: velero-s3-credentials

upgradeCRDs: false
kubectl:
  image:
    repository: bitnami/kubectl
    tag: latest@sha256:b9f4412e53f09d76b0991cdd29c0feff4c1d1e112b307e0ab155e5b050a9f4ec


schedules:
  media-pvc-backup:
    disabled: false
    schedule: "0 3 * * *" # Daily at 3 AM
    template:
      includedNamespaces:
        - media
      includedResources:
        - persistentvolumeclaims
        - persistentvolumes
        - pods
      
      resourcePolicy:
        kind: configmap
        name: longhorn-volume-policy

