global:
  domain: "miquella.dev"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

mc-router:
  enabled: true
  image:
    repository: "itzg/mc-router"
    tag: "1.44.0@sha256:74c0f682cb45a1ac7ac25082c63f236bd6b04395508ad41d5825fd8cc8828b8f"
  watchNamespace: "game-servers"

minecraft-vanilla:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.9.1@sha256:e8640538dac5d54c2838d57fa9641e735ad0cf2b71fb0e8a68da3b542a315749"
  port: "25565"
  subdomain: "vanilla"
  type: "VANILLA"
  version: "26.1.1"
  memory: "3G"
  storageSize: "5Gi"


minecraft-modded:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.9.1@sha256:e8640538dac5d54c2838d57fa9641e735ad0cf2b71fb0e8a68da3b542a315749"
  port: "25565"
  subdomain: "modded"
  type: "NEOFORGE"
  version: "1.21.1"
  memory: "6G"
  storageSize: "5Gi"
