global:
  domain: "miquella.dev"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

mc-router:
  enabled: true
  image:
    repository: "itzg/mc-router"
    tag: "1.47.2@sha256:64ae69eaa7a6800a79bbf962f027f4020878efa25183359115bc7f6ee569c36e"
  watchNamespace: "game-servers"

minecraft-vanilla:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.10.0@sha256:5a2ab74ae179c11e2dbbce67f307cdcf2c1257b3abb0f654d3a310b3d8ea57da"
  port: "25565"
  subdomain: "vanilla"
  type: "VANILLA"
  version: "26.1.1"
  memory: "3G"
  storageSize: "5Gi"


minecraft-modded:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.10.0@sha256:5a2ab74ae179c11e2dbbce67f307cdcf2c1257b3abb0f654d3a310b3d8ea57da"
  port: "25565"
  subdomain: "modded"
  type: "NEOFORGE"
  version: "1.21.1"
  memory: "6G"
  storageSize: "5Gi"
