global:
  domain: "miquella.dev"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

mc-router:
  enabled: true
  image:
    repository: "itzg/mc-router"
    tag: "1.46.5@sha256:e06735ea74877a7de649bcaec4cb917bf952564d32cbe258670fb7753192a1e9"
  watchNamespace: "game-servers"

minecraft-vanilla:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.6.1@sha256:2a3ed0997720d79b7ed783a79e43143358b2e60d27daf15c2b1d27b59d04a6d8"
  port: "25565"
  subdomain: "vanilla"
  type: "VANILLA"
  version: "26.1.1"
  memory: "3G"
  storageSize: "5Gi"


minecraft-modded:
  enabled: true
  image:
    repository: "ghcr.io/itzg/minecraft-server"
    tag: "2026.6.1@sha256:2a3ed0997720d79b7ed783a79e43143358b2e60d27daf15c2b1d27b59d04a6d8"
  port: "25565"
  subdomain: "modded"
  type: "NEOFORGE"
  version: "1.21.1"
  memory: "6G"
  storageSize: "5Gi"
