---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    CLOUDFLARE_DNS_API_TOKEN: AgCQ0Z4IMg+72ox5Lcm4rqT2QgRf/oGdCoahRsBkdGeG4VkUbL5fGKCGP2lD8jeDZ54nQ/xI69XvKc3HBas9rEOgkmDLozkzFNPTtTtdXlpNaGBJrUAXR3tKRdijZAmx5D+VxXeF0yCwqEeRWtBtxCrWhCXqXJUr0rVrYtYVEHkMcL3tiuwwe8YVHqbkTLm5WxnFPyAmmNA0FhIRUU1v9Rw1XzMGbVckxZIoqUpd7ekWS4GH9GzVw2nIQzs0GjCyWjITmYEzQZK57W5Hx4CNbIkYR9yp9VpFtFWfl86itOHIbqwSTKaOrjw92vHZba3ZAXq3NshE5Yl6DuzO676Dr8hWVyfCIcmsEZtcRf960fRFU9j1kWPh9scoLhI9IPJYYT+ruvDVEZy6sfl+Bf/0ZyQ3Pl+iYjsQdsl41xljWugbgVzvQn23Iot1AjeRlWNeUCmZ7vwrBW8qn/czHs1eIP2aGMCaLxRpeGQOJgi2TK5mPj6j2lPIFEiR9Afcm1tN+dwmQHEdsDWm2mKzf+/of6GNR8AaTHXfeXQK+hlFsTPhfVZ5VYzPjHUqlpS9rnT5ax7koDqKuwBcIJuWEPX3vTKbliWDBqR/6CPIV/xXlJc8mIiI1MMOKWHHMbZq055QQ9rHFQvMqZ27Rp9IGdqWsUYo3Ky7MiMizoc/B9unzdNptPT0LSdEgT5pB2Nh+tOpdZ7+qJdo+30Oj8/5DrbmX4HfENkE7Cq0/hV5yWs2DTRMZ+whwwtW6BL/Gi6AouJ8tDjPRsc+RQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: kube-system
