apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Chart.Name }}-auth
    creationPolicy: Owner
  data:
    - secretKey: CUSTOM_USER
      remoteRef:
        key: {{ .Chart.Name }}-auth/username
    - secretKey: PASSWORD
      remoteRef:
        key: {{ .Chart.Name }}-auth/password
