apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-whitelist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minecraft-whitelist
    creationPolicy: Owner
  data:
    - secretKey: names
      remoteRef:
        key: minecraft-whitelist/names
