apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    mc-router.itzg.me/externalServerName: "{{ .Values.subdomain }}.{{ .Values.global.domain }}"
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: minecraft
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
