---
apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-volume-policy
  namespace: velero
data:
  policies.yaml: |
    version: v1
    volumePolicies:
    # Match LINSTOR and take a CSI snapshot (moved to object storage)
    - conditions:
        storageClass:
          - linstor
      action:
        type: snapshot
    # Catch-all: skip data backup for all other storage classes (e.g. smb)
    - conditions: {}
      action:
        type: skip
