---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCXdL2zblfxf9t7P22Aqdz7obX/X0dLL+PvCepvfX8QwuRgMz/bSvnxr9O9S1DsFaxyebkGR6FPD5Jxqe9T5LHzt3smxj6rFG/7H2klgwhMp4tbCxieXoMttBqSIBNnz3zXW4q6dPimI3YUU2wywUeWhe5kKE+8FCvewuhTLkWVK99YKCzp4rgLJEavntoisRkEywZGOv8EJMS2zR29lVzWiDA5ydKqcSdfn2IbPDotjLHLQVsyc80C1/0DmWazs/pimwiy3HdtypcbeUthYCn9OEw2sVYFk0MAOqwGNucv6YA51TmiV/QFcQLVE78hJ2EysYnV/dUsem2D4p60bsas+VlQx5lONKMfJ7Fb82B71LJ+0JhZZeF1hh59hVmRRDnFQT5cyIRib7HcvQJmbuSduSxXi60GxtIzjT9XOxQtn1RNr1s2mjJPflIXivW0aDfVYQC8Devr1xUhJMjOmdtBJReU3BYNwzjsrUNDpPkotXHoxU4dIZ17WYVWKKrmZzu61z5B/MusD1MAV6Rp3JXM3A3ihGIx1AUsFlG7mUCD2LQlXJT7O9G0yV9i/mIjoA/5ctV8KLtOWqvKVfZdwnEZGHVlVbHGQzbIenYLFCdjir9pMRelqxvG3J8OvJ2kXIt/14b81K0HoZEVZOGNLcHJd+N8jNO2feJq3ppzCRq6Akq2arRrXWqmdQhmEpVssqkZYP24PgOnAn/nnoMIeiqmmILLmjbsTAW7JcLbmHT3PVfeaQohoUSdAJV1GWyzhWxCMOzFryurJNrJ/LCJdR8jD/5jMNUHqWJL346Z05R4QMOfJqBr5HVIsIpVeZSKzmWdNV4RMTqSjo2uGno6XVL0eE6t3Lxgqqni6l9bfV0nxEN/MkFyNP3dGZld/wfbqlpNQF62
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
