---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA5oMyR2yTgGDaQD0edSiqohyA/dDWA7nApa8gIJQx+NU2jV6Y/aEyPudX7qtsyUPIYvWIH/ncqDQFz8K+VtNg+FbUl8MlQAQosu5r6SkV+UDAbS239pSnhqoXUJiuivRWJwPyum8b0/ai5CQ3R/8VHktoY+ESA1E0tsL8LN/B8/2M0TIlmO/arPqd+xjTrIRgHrcVIQJlMWxKpgbqGPGMDzxNipO5lHfeia43cgh/f/f8Tsd8LtYqHRATLC8AWAnKShDTzgIiejE5yY31zbQJkRuuMiGl5Gbd1YoLJdIVGAGAu7wCCeyAOXUsi4CTHG/pxx8AvrMys4lD+IHKcANVd89vRIhoyrUFxegePAy3SmCr/U0BqCx72JvVWyI8hufIGfY58azQrOftJLFqoYN1R20gHjEXnMz/ul0yjXSaDAS512jcQon4XadQEU6hKiKKXDmAP8EnANNSobaiS1GQVcbz+chpupQDJCMx27GxJoGqyfe9YM4+UamuBCvYdu51B7zMnWtn8iLEUnyXFiJNIoMXBy5Y7GNCjJJWNZLK/TZoGzWGkv79Gp1qGQU9i8c4SaSXgOMJrve2FULNJGpU7BqU+tUXinVlOjbstPY90ARGE2P+e7RcH3i0wrUQjFFMZg3MZTf4tUwxfvgkQA6jMF7Wno9XkjkqWC/+tlBiQpCMNxkmgBIfYfdq/Qh2vDdaCFZWwn9PyE1vVwWMv0Z9p0OdZVQgDCt8N9FcZf4cyp9BP5SHYMM0iDH2Eg4jwHbjcHUZRRYkHWIWcM6sgS8kr1BXV69xsxZjMzcqa0IOrHZX99FZnHZw4y+OJLev3e7d5LoK59gUbBJ5Na7dzs1Zgf2w2VbtHVK0/rcCBCt06PFhlwNlEfCm3P9ZWuEiplIs8jSWh
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
