apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.prowlarr.subdomain }}.miquella.dev`)
      kind: Rule
      services:
        - name: prowlarr
          port: {{ .Values.prowlarr.port }}
  tls: {}
